"""Starter-scene facts for CH-01-001 through CH-01-016."""

from __future__ import annotations

SCENES = [
    {
        "entry_id": "CH-01-001",
        "caption": "Matterhorn, Zermatt",
        "city": "Zermatt",
        "region": "Valais",
        "folder": "Zermatt",
        "lat": 45.9834,
        "lon": 7.7826,
        "viewpoint": "Gornergrat railway terrace, looking southwest toward the Matterhorn. Map: https://maps.google.com/?q=45.9834,7.7826 The exact paving stone was not surveyed.",
        "refs": [
            "https://www.gornergrat.ch/en/",
            "https://en.wikipedia.org/wiki/Matterhorn",
        ],
        "anchors": [
            "Asymmetric pyramidal horn; from Gornergrat the Hörnli ridge descends on the right skyline of the peak.",
            "Gorner Glacier in the middle ground, crevassed ice with gray moraines, below the peak.",
            "Rocky Gornergrat foreground; no invented cableway or construction crane.",
        ],
        "composition": "Gornergrat railway terrace looking southwest toward the Matterhorn and Gorner Glacier · AI-generated artistic interpretation",
        "description": "From the Gornergrat railway terrace, looking southwest, the Matterhorn rises as a dark pyramidal horn with snow and ice on the upper faces and the Hörnli ridge falling to the right. The Gorner Glacier fills the middle ground with crevassed ice and gray moraine. Late-September rock and tawny alpine grass occupy the near slope under the Open-Meteo cloud and temperature for this high cell. No new construction is shown.",
        "alt_text": "AI-generated artistic interpretation of the Matterhorn from the Gornergrat railway terrace above Zermatt",
        "sky": "Partly cloudy high-alpine afternoon, patches of blue with fair-weather cumulus, sun high from the south-southwest, cool clear air, no falling snow, tawny September turf rather than midsummer flowers.",
        "weather_note": "Gornergrat station is about 3135 m; the Open-Meteo cell is about 3057 m, so the temperature is the model cell, not a thermometer on the terrace.",
    },
    {
        "entry_id": "CH-01-002",
        "caption": "Chapel Bridge, Lucerne",
        "city": "Lucerne",
        "region": "Lucerne",
        "folder": "Lucerne",
        "lat": 47.0516,
        "lon": 8.3074,
        "viewpoint": "Reuss bank beside the Chapel Bridge, looking along the covered span toward the Water Tower. Map: https://maps.google.com/?q=47.0516,8.3074 The exact camera point was not surveyed.",
        "refs": [
            "https://www.luzern.com/en/",
            "https://en.wikipedia.org/wiki/Chapel_Bridge",
        ],
        "anchors": [
            "Covered wooden bridge with a dark roof crossing the Reuss diagonally.",
            "Octagonal stone Water Tower standing in the river at the bridge.",
            "Old-town facades beyond the water; the bridge is intact, with no fire ruin and no scaffolding.",
        ],
        "composition": "Reuss crossing with the covered wooden Chapel Bridge and octagonal Water Tower · AI-generated artistic interpretation",
        "description": "The covered wooden Chapel Bridge runs diagonally across the Reuss, with the octagonal stone Water Tower standing in the river beside it. Flower boxes line the bridge and the old-town facades sit beyond the water. The walkway is empty of prominent people, and the bridge is shown in its standing rebuilt form, without fire damage or scaffolding. Cloud and light follow the Open-Meteo model for this Lucerne afternoon.",
        "alt_text": "AI-generated artistic interpretation of the Chapel Bridge and Water Tower on the Reuss in Lucerne",
        "sky": "Fully overcast afternoon, soft diffuse light, gray sky, no blue patches, no rain shafts, no hard shadows.",
    },
    {
        "entry_id": "CH-01-003",
        "caption": "Jungfrau, Interlaken",
        "city": "Interlaken",
        "region": "Bern",
        "folder": "Interlaken",
        "lat": 46.6958,
        "lon": 7.8642,
        "viewpoint": "Harder Kulm terrace north of Interlaken, looking south across the town toward the Jungfrau massif. Map: https://maps.google.com/?q=46.6958,7.8642 The exact railing position was not surveyed.",
        "refs": [
            "https://harderkulm.ch/",
            "https://en.wikipedia.org/wiki/Jungfrau",
        ],
        "anchors": [
            "Interlaken in the valley between Lake Brienz (east, left) and Lake Thun (west, right).",
            "Looking south: Eiger’s dark wall on the left, Mönch in the center, snowier Jungfrau on the right.",
            "High peaks carry cloud under the overcast model; the town is not snow-covered.",
        ],
        "composition": "Harder Kulm panorama south over Interlaken toward Eiger, Mönch, and Jungfrau · AI-generated artistic interpretation",
        "description": "From the Harder Kulm terrace north of Interlaken, the view looks south across the town between Lake Brienz and Lake Thun. Eiger’s dark wall, the Mönch, and the snowier Jungfrau stand in that order from left to right, with cloud on the high faces. The lakes and valley remain readable below. The peaks are shown with cloud because the Open-Meteo model for this afternoon is overcast, not as a clear-day postcard.",
        "alt_text": "AI-generated artistic interpretation of the Jungfrau massif from Harder Kulm above Interlaken under cloud",
        "sky": "Overcast afternoon, gray sky, diffuse light, summits wrapped in cloud but still identifiable, green valley, no fresh snow on the town.",
        "weather_note": "Harder Kulm terrace is about 1322 m. The Open-Meteo cell elevation is about 905 m, so the temperature is the model cell, not a reading on the terrace.",
    },
    {
        "entry_id": "CH-01-004",
        "caption": "Jet d'Eau, Geneva",
        "city": "Geneva",
        "region": "Geneva",
        "folder": "Geneva",
        "lat": 46.2074,
        "lon": 6.1560,
        "viewpoint": "Geneva quay on Lake Geneva, looking toward the offshore Jet d'Eau. Map: https://maps.google.com/?q=46.2074,6.1560 The exact quay stone was not surveyed.",
        "refs": [
            "https://www.geneve.com/en/",
            "https://en.wikipedia.org/wiki/Jet_d%27Eau",
        ],
        "anchors": [
            "One vertical water plume rising from a small structure in the lake, not a multi-jet plaza fountain.",
            "Open lake water between the quay and the jet.",
            "Low far shore; no flower clock and no readable emblem as the subject.",
        ],
        "composition": "Lakefront quay looking toward the single Jet d'Eau plume on Lake Geneva · AI-generated artistic interpretation",
        "description": "A single tall water plume rises from the jet structure offshore in Lake Geneva, seen from the Geneva quay. The lake stretches toward a low far shore under cloud. The jet is the only fountain, and the frame does not include the flower clock or a focal logo. Light is the soft overcast described by the Open-Meteo model for this Geneva afternoon.",
        "alt_text": "AI-generated artistic interpretation of the Jet d'Eau rising from Lake Geneva",
        "sky": "Overcast afternoon, gray sky, soft light, gray-blue lake, no rain, no second fountain.",
    },
    {
        "entry_id": "CH-01-005",
        "caption": "Zytglogge, Bern",
        "city": "Bern",
        "region": "Bern",
        "folder": "Bern",
        "lat": 46.9480,
        "lon": 7.4478,
        "viewpoint": "Kramgasse in Bern’s old town, looking west toward the Zytglogge. Map: https://maps.google.com/?q=46.9480,7.4478 The exact arcade bay was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Zytglogge",
            "https://whc.unesco.org/en/list/267/",
        ],
        "anchors": [
            "Sandstone arcade street of the old town closing on a clock tower.",
            "Zytglogge astronomical clock and pointed tower at the west end of Kramgasse.",
            "No festival banners and no scaffolding added to the UNESCO street.",
        ],
        "composition": "Kramgasse looking west to the Zytglogge clock tower · AI-generated artistic interpretation",
        "description": "The sandstone arcade of Bern’s Kramgasse leads west to the Zytglogge, whose astronomical clock and pointed tower close the street. The old-town roofs stay inside the street canyon. No festival banners or scaffolding are added. The afternoon light is the diffuse overcast given by the Open-Meteo model for Bern.",
        "alt_text": "AI-generated artistic interpretation of the Zytglogge at the end of Kramgasse in Bern",
        "sky": "Overcast afternoon, soft gray light on sandstone, no blue sky, no rain.",
    },
    {
        "entry_id": "CH-01-006",
        "caption": "Limmatquai, Zurich",
        "city": "Zurich",
        "region": "Zurich",
        "folder": "Zurich",
        "lat": 47.3695,
        "lon": 8.5428,
        "viewpoint": "Limmatquai on the right bank of the Limmat, looking along the river with the Grossmünster towers. Map: https://maps.google.com/?q=47.3695,8.5428 The exact quay point was not surveyed.",
        "refs": [
            "https://www.zuerich.com/en/visit/attractions/grossmunster",
            "https://en.wikipedia.org/wiki/Limmatquai",
        ],
        "anchors": [
            "Limmat river with the quay promenade along the right bank.",
            "Grossmünster’s pair of Romanesque towers on the right-bank rise.",
            "Guild-house facades on the water; no commercial logo as the subject.",
        ],
        "composition": "Limmatquai looking along the Limmat toward the Grossmünster twin towers · AI-generated artistic interpretation",
        "description": "The Limmatquai promenade follows the Limmat through Zurich’s old town, with guild-house facades on the water and the Grossmünster’s twin Romanesque towers on the right bank. The river runs through the frame and the quay is free of prominent people. No commercial logo is the subject. Cloud and temperature follow the Open-Meteo model for this Zurich afternoon.",
        "alt_text": "AI-generated artistic interpretation of Limmatquai and the Grossmünster along the Limmat in Zurich",
        "sky": "Overcast afternoon, gray sky, diffuse light, slight breeze on the river, no rain.",
    },
    {
        "entry_id": "CH-01-007",
        "caption": "Staubbach Falls, Lauterbrunnen",
        "city": "Lauterbrunnen",
        "region": "Bern",
        "folder": "Lauterbrunnen",
        "lat": 46.5932,
        "lon": 7.9087,
        "viewpoint": "Lauterbrunnen valley floor looking up at Staubbach Falls on the western cliff. Map: https://maps.google.com/?q=46.5932,7.9087 The exact meadow point was not surveyed.",
        "refs": [
            "https://www.jungfrau.ch/en-gb/",
            "https://en.wikipedia.org/wiki/Staubbach_Falls",
        ],
        "anchors": [
            "Very tall, thin waterfall leaving the lip of a sheer cliff.",
            "Wooden chalets and a church spire at the foot of the wall.",
            "Narrow valley, late-September green meadow, not a wide river cataract.",
        ],
        "composition": "Valley floor looking up at Staubbach Falls above the Lauterbrunnen church · AI-generated artistic interpretation",
        "description": "Staubbach Falls drops as a tall, thin veil from the lip of the western cliff above Lauterbrunnen. Wooden chalets and the church spire sit at the base of the wall, with late-September meadows still green. The fall is the cliff waterfall, not a wide river cataract. The Open-Meteo model for the valley is heavily clouded, and the light is soft.",
        "alt_text": "AI-generated artistic interpretation of Staubbach Falls above Lauterbrunnen",
        "sky": "Heavily overcast afternoon, gray sky, soft light, green valley meadows, no blue sky, no rain curtain beyond the waterfall mist.",
    },
    {
        "entry_id": "CH-01-008",
        "caption": "Gruyères Castle, Gruyères",
        "city": "Gruyères",
        "region": "Fribourg",
        "folder": "Gruyères",
        "lat": 46.5834,
        "lon": 7.0837,
        "viewpoint": "Medieval main street of Gruyères, looking uphill toward the castle. Map: https://maps.google.com/?q=46.5834,7.0837 The exact cobble was not surveyed.",
        "refs": [
            "https://www.chateau-gruyeres.ch/en/",
            "https://en.wikipedia.org/wiki/Gruy%C3%A8res_Castle",
        ],
        "anchors": [
            "Hill town street of medieval houses leading to a castle at the high end.",
            "Castle with round towers and steep roofs above the roofs of the town.",
            "Fribourg pre-Alps behind; no scaffolding on the castle.",
        ],
        "composition": "Medieval street climbing to Gruyères Castle on the hill · AI-generated artistic interpretation",
        "description": "The cobbled main street of Gruyères rises between medieval houses to the castle at the top of the hill, with round towers and steep roofs. The Fribourg pre-Alps sit behind the town. The castle is shown as it stands, without added scaffolding, and the street has no prominent people. Afternoon light is the soft overcast from the Open-Meteo model.",
        "alt_text": "AI-generated artistic interpretation of Gruyères Castle above the medieval street in Gruyères",
        "sky": "Overcast afternoon, gray sky, soft light on stone and plaster, green pre-Alps under cloud.",
    },
    {
        "entry_id": "CH-01-009",
        "caption": "Chillon Castle, Montreux",
        "city": "Montreux",
        "region": "Vaud",
        "folder": "Montreux",
        "lat": 46.4142,
        "lon": 6.9274,
        "viewpoint": "Lake Geneva shore near Montreux, looking toward Chillon Castle on its rock. Map: https://maps.google.com/?q=46.4142,6.9274 The exact shore point was not surveyed.",
        "refs": [
            "https://www.chillon.ch/en/",
            "https://en.wikipedia.org/wiki/Chillon_Castle",
        ],
        "anchors": [
            "Castle on a rock island in Lake Geneva, round and square towers, bridge to the shore.",
            "Water reaching the walls.",
            "Dents du Midi ridge across the lake, softened by cloud.",
        ],
        "composition": "Lake Geneva shore looking toward Chillon Castle and the Dents du Midi · AI-generated artistic interpretation",
        "description": "Chillon Castle stands on its rock in Lake Geneva, a cluster of round and square towers linked to the shore by a bridge. The water reaches the walls, and the Dents du Midi ridge is the mountain backdrop across the lake. The peaks are softened by cloud to match the overcast Open-Meteo model. No boat with a readable name is featured.",
        "alt_text": "AI-generated artistic interpretation of Chillon Castle on Lake Geneva near Montreux",
        "sky": "Overcast afternoon, gray sky, soft light, mountains hazy with cloud, lake gray-blue, no rain.",
    },
    {
        "entry_id": "CH-01-010",
        "caption": "Lake St. Moritz, St. Moritz",
        "city": "St. Moritz",
        "region": "Graubünden",
        "folder": "St. Moritz",
        "lat": 46.4970,
        "lon": 9.8380,
        "viewpoint": "Shore of Lake St. Moritz, looking across the water toward the town and Engadin peaks. Map: https://maps.google.com/?q=46.4970,9.8380 The exact shore point was not surveyed.",
        "refs": [
            "https://www.stmoritz.com/en/",
            "https://en.wikipedia.org/wiki/St._Moritz",
        ],
        "anchors": [
            "Alpine lake in the foreground and the town on the slope.",
            "Engadin peaks behind the town, with residual snow only on higher summits.",
            "Late September: larches mostly green with first gold, town not in winter snow cover.",
        ],
        "composition": "Engadin lakeshore looking across Lake St. Moritz toward the town and peaks · AI-generated artistic interpretation",
        "description": "Lake St. Moritz fills the foreground, with the town climbing the slope and high Engadin peaks behind it. Late September here is early autumn: larches are still mostly green with only the first gold, and the town is not under winter snow. Residual snow is limited to the higher summits. The Open-Meteo model for this high cell is fully overcast.",
        "alt_text": "AI-generated artistic interpretation of Lake St. Moritz and the Engadin town under cloud",
        "sky": "Fully overcast afternoon at altitude, gray sky, no blue, town and lake free of winter snow, only high summits holding residual snow, larches just starting to turn.",
    },
    {
        "entry_id": "CH-01-011",
        "caption": "Appenzell, Appenzell",
        "city": "Appenzell",
        "region": "Appenzell Innerrhoden",
        "folder": "Appenzell",
        "lat": 47.3314,
        "lon": 9.4096,
        "viewpoint": "Appenzell village center, looking across painted wooden houses toward the Alpstein. Map: https://maps.google.com/?q=47.3314,9.4096 The exact square point was not surveyed.",
        "refs": [
            "https://www.appenzell.ch/en/",
            "https://en.wikipedia.org/wiki/Appenzell_(village)",
        ],
        "anchors": [
            "Painted wooden gables and a village church, not a generic chalet row.",
            "Limestone ridges of the Alpstein behind the roofs.",
            "Public square without prominent people.",
        ],
        "composition": "Village center with painted wooden houses and the Alpstein behind · AI-generated artistic interpretation",
        "description": "Appenzell’s village center shows painted wooden gables and the church, with the limestone ridges of the Alpstein rising behind the roofs. The street is a public square, empty of prominent people. Houses keep traditional painted fronts rather than a generic chalet row. The Open-Meteo model is overcast and breezy for this afternoon.",
        "alt_text": "AI-generated artistic interpretation of Appenzell village with painted houses and the Alpstein",
        "sky": "Overcast and breezy afternoon, gray sky, soft light, green pastures, Alpstein limestone partly in cloud.",
    },
    {
        "entry_id": "CH-01-012",
        "caption": "Lugano lakefront, Lugano",
        "city": "Lugano",
        "region": "Ticino",
        "folder": "Lugano",
        "lat": 46.0037,
        "lon": 8.9511,
        "viewpoint": "Lugano lakefront promenade, looking across the lake toward Monte Brè and Monte San Salvatore. Map: https://maps.google.com/?q=46.0037,8.9511 The exact promenade point was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Lugano",
            "https://en.wikipedia.org/wiki/Monte_Br%C3%A8",
        ],
        "anchors": [
            "Lake Lugano with a palm-lined promenade in the foreground.",
            "Monte Brè and Monte San Salvatore framing the water.",
            "Subtropical lakeside vegetation still green in late September; mountains softened by cloud.",
        ],
        "composition": "Lugano lakefront promenade toward the lake, Monte Brè, and Monte San Salvatore · AI-generated artistic interpretation",
        "description": "The Lugano lakefront promenade faces Lake Lugano, with palms and waterfront buildings in front of Monte Brè and Monte San Salvatore. Ticino vegetation is still green in late September. The mountains are close and partly softened by cloud. The Open-Meteo model for this afternoon is overcast, with little wind and no rain.",
        "alt_text": "AI-generated artistic interpretation of the Lugano lakefront with Monte Brè under cloud",
        "sky": "Overcast afternoon, gray sky, soft light, green palms, lake gray-blue, mountains close and cloud-softened, no rain.",
    },
    {
        "entry_id": "CH-01-013",
        "caption": "Mittlere Brücke, Basel",
        "city": "Basel",
        "region": "Basel-Stadt",
        "folder": "Basel",
        "lat": 47.5596,
        "lon": 7.5903,
        "viewpoint": "Rhine bank in Basel looking along Mittlere Brücke toward the chapel on the bridge and the Münster. Map: https://maps.google.com/?q=47.5596,7.5903 The exact quay point was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Mittlere_Br%C3%BCcke",
            "https://en.wikipedia.org/wiki/Basel_Minster",
        ],
        "anchors": [
            "Stone bridge across the Rhine with a small chapel on the bridge.",
            "Red-sandstone Basel Münster on the rise above the south bank.",
            "No commercial banners added to the bridge.",
        ],
        "composition": "Rhine and Mittlere Brücke with the bridge chapel and Basel Münster · AI-generated artistic interpretation",
        "description": "The Mittlere Brücke crosses the Rhine in Basel, with the small chapel on the bridge and the red-sandstone Basel Münster on the rise above the south bank. The quays are quiet and no commercial banners are added to the bridge. The Open-Meteo model for this afternoon is overcast and windy, with no rain.",
        "alt_text": "AI-generated artistic interpretation of Mittlere Brücke and Basel Münster on the Rhine",
        "sky": "Overcast windy afternoon, gray sky, soft light, gray-green Rhine, no rain.",
    },
    {
        "entry_id": "CH-01-014",
        "caption": "Thun Castle, Thun",
        "city": "Thun",
        "region": "Bern",
        "folder": "Thun",
        "lat": 46.7584,
        "lon": 7.6298,
        "viewpoint": "Thun old town toward the castle keep, with the Aare and a glimpse of the lake. Map: https://maps.google.com/?q=46.7584,7.6298 The exact street point was not surveyed.",
        "refs": [
            "https://schlossthun.ch/",
            "https://en.wikipedia.org/wiki/Thun_Castle",
        ],
        "anchors": [
            "Massive square keep with four corner towers and steep roofs above the roofs.",
            "Aare river through the town toward Lake Thun.",
            "Alps only faint under cloud; no construction cranes on the castle.",
        ],
        "composition": "Old town and Aare toward Thun Castle, with Lake Thun beyond · AI-generated artistic interpretation",
        "description": "Thun Castle’s great square keep and four corner towers rise above the old-town roofs. The Aare runs through the town toward Lake Thun, with the Alps faint under cloud. The castle is the historic keep, without construction cranes. The Open-Meteo model for this afternoon is overcast.",
        "alt_text": "AI-generated artistic interpretation of Thun Castle above the old town and the Aare",
        "sky": "Overcast afternoon, gray sky, soft light, lake and river visible, Alps only a faint shape in cloud.",
    },
    {
        "entry_id": "CH-01-015",
        "caption": "Eiger, Grindelwald",
        "city": "Grindelwald",
        "region": "Bern",
        "folder": "Grindelwald",
        "lat": 46.6242,
        "lon": 8.0414,
        "viewpoint": "Grindelwald valley meadows, looking south at the Eiger north face. Map: https://maps.google.com/?q=46.6242,8.0414 The exact meadow point was not surveyed. Weather cell is the valley, not the summit.",
        "refs": [
            "https://grindelwald.swiss/en/",
            "https://en.wikipedia.org/wiki/Eiger",
        ],
        "anchors": [
            "Eiger north face as a dark near-vertical wall, not a generic snow pyramid.",
            "Mönch and Jungfrau further west (right when looking south); Wetterhorn to the east (left).",
            "Valley meadows and chalets in late-September green; no invented climbing infrastructure on the wall.",
        ],
        "composition": "Grindelwald meadows looking south at the Eiger north face · AI-generated artistic interpretation",
        "description": "From the Grindelwald valley, the Eiger’s north face is a dark, near-vertical wall, with the Mönch and Jungfrau further west and the Wetterhorn to the east. Meadows and wooden chalets sit in the foreground under late-September green. The Open-Meteo valley model is overcast with partial cloud cover, so the upper wall carries cloud while the face stays identifiable. No climbing infrastructure is invented on the wall.",
        "alt_text": "AI-generated artistic interpretation of the Eiger north face from Grindelwald",
        "sky": "Valley overcast with breaks, gray sky, upper north face wearing cloud, lower rock wall visible, green meadows, no midwinter snow in the village.",
    },
    {
        "entry_id": "CH-01-016",
        "caption": "Rhine Falls, Schaffhausen",
        "city": "Schaffhausen",
        "region": "Schaffhausen",
        "folder": "Schaffhausen",
        "lat": 47.6779,
        "lon": 8.6155,
        "viewpoint": "North-bank viewpoint at the Rhine Falls, looking across the falls toward Schloss Laufen. Map: https://maps.google.com/?q=47.6779,8.6155 The exact platform was not surveyed.",
        "refs": [
            "https://www.rheinfall.ch/en/",
            "https://en.wikipedia.org/wiki/Rhine_Falls",
        ],
        "anchors": [
            "Wide falls breaking around a central rock in the Rhine.",
            "Schloss Laufen on the south cliff and Schloss Wörth on the near bank.",
            "Only the real visitor railings at the viewpoint; no extra invented scaffolding.",
        ],
        "composition": "Rhine Falls from the north bank, with the mid-river rock and Schloss Laufen · AI-generated artistic interpretation",
        "description": "The Rhine Falls spreads wide across the river, breaking around the central rock, with Schloss Laufen on the south cliff and Schloss Wörth on the near side. Existing visitor railings belong to the real viewpoint and are not expanded into new scaffolding. Spray and gray water match a cloudy afternoon. The Open-Meteo model is overcast and windy, with no rain.",
        "alt_text": "AI-generated artistic interpretation of the Rhine Falls near Schaffhausen",
        "sky": "Overcast windy afternoon, gray sky, soft light, gray water and spray, no blue sky, no rain shafts.",
    },
]
