"""Scene facts for CH-01-001 through CH-01-032."""

from __future__ import annotations

SCENES = [
    {
        "entry_id": "CH-01-001",
        "caption": "Matterhorn, Zermatt",
        "city": "Zermatt",
        "region": "Valais",
        "folder": "Zermatt",
        "lat": 45.9834,
        "lon": 7.7826,
        "viewpoint": "Gornergrat railway terrace, looking southwest toward the Matterhorn. Map: https://maps.google.com/?q=45.9834,7.7826 The exact paving stone was not surveyed.",
        "refs": [
            "https://www.gornergrat.ch/en/",
            "https://en.wikipedia.org/wiki/Matterhorn",
        ],
        "anchors": [
            "Asymmetric pyramidal horn; from Gornergrat the Hörnli ridge descends on the right skyline of the peak.",
            "Gorner Glacier in the middle ground, crevassed ice with gray moraines, below the peak.",
            "Rocky Gornergrat foreground; no invented cableway or construction crane.",
        ],
        "composition": "Gornergrat railway terrace looking southwest toward the Matterhorn and Gorner Glacier · AI-generated artistic interpretation",
        "description": "From the Gornergrat railway terrace, looking southwest, the Matterhorn rises as a dark pyramidal horn with snow and ice on the upper faces and the Hörnli ridge falling to the right. The Gorner Glacier fills the middle ground with crevassed ice and gray moraine. Late-September rock and tawny alpine grass occupy the near slope under the Open-Meteo cloud and temperature for this high cell. No new construction is shown.",
        "alt_text": "AI-generated artistic interpretation of the Matterhorn from the Gornergrat railway terrace above Zermatt",
        "sky": "Partly cloudy high-alpine afternoon, patches of blue with fair-weather cumulus, sun high from the south-southwest, cool clear air, no falling snow, tawny September turf rather than midsummer flowers.",
        "weather_note": "Gornergrat station is about 3135 m; the Open-Meteo cell is about 3057 m, so the temperature is the model cell, not a thermometer on the terrace.",
    },
    {
        "entry_id": "CH-01-002",
        "caption": "Chapel Bridge, Lucerne",
        "city": "Lucerne",
        "region": "Lucerne",
        "folder": "Lucerne",
        "lat": 47.0516,
        "lon": 8.3074,
        "viewpoint": "Reuss bank beside the Chapel Bridge, looking along the covered span toward the Water Tower. Map: https://maps.google.com/?q=47.0516,8.3074 The exact camera point was not surveyed.",
        "refs": [
            "https://www.luzern.com/en/",
            "https://en.wikipedia.org/wiki/Chapel_Bridge",
        ],
        "anchors": [
            "Covered wooden bridge with a dark roof crossing the Reuss diagonally.",
            "Octagonal stone Water Tower standing in the river at the bridge.",
            "Old-town facades beyond the water; the bridge is intact, with no fire ruin and no scaffolding.",
        ],
        "composition": "Reuss crossing with the covered wooden Chapel Bridge and octagonal Water Tower · AI-generated artistic interpretation",
        "description": "The covered wooden Chapel Bridge runs diagonally across the Reuss, with the octagonal stone Water Tower standing in the river beside it. Flower boxes line the bridge and the old-town facades sit beyond the water. The walkway is empty of prominent people, and the bridge is shown in its standing rebuilt form, without fire damage or scaffolding. Cloud and light follow the Open-Meteo model for this Lucerne afternoon.",
        "alt_text": "AI-generated artistic interpretation of the Chapel Bridge and Water Tower on the Reuss in Lucerne",
        "sky": "Fully overcast afternoon, soft diffuse light, gray sky, no blue patches, no rain shafts, no hard shadows.",
    },
    {
        "entry_id": "CH-01-003",
        "caption": "Jungfrau, Interlaken",
        "city": "Interlaken",
        "region": "Bern",
        "folder": "Interlaken",
        "lat": 46.6958,
        "lon": 7.8642,
        "viewpoint": "Harder Kulm terrace north of Interlaken, looking south across the town toward the Jungfrau massif. Map: https://maps.google.com/?q=46.6958,7.8642 The exact railing position was not surveyed.",
        "refs": [
            "https://harderkulm.ch/",
            "https://en.wikipedia.org/wiki/Jungfrau",
        ],
        "anchors": [
            "Interlaken in the valley between Lake Brienz (east, left) and Lake Thun (west, right).",
            "Looking south: Eiger’s dark wall on the left, Mönch in the center, snowier Jungfrau on the right.",
            "High peaks carry cloud under the overcast model; the town is not snow-covered.",
        ],
        "composition": "Harder Kulm panorama south over Interlaken toward Eiger, Mönch, and Jungfrau · AI-generated artistic interpretation",
        "description": "From the Harder Kulm terrace north of Interlaken, the view looks south across the town between Lake Brienz and Lake Thun. Eiger’s dark wall, the Mönch, and the snowier Jungfrau stand in that order from left to right, with cloud on the high faces. The lakes and valley remain readable below. The peaks are shown with cloud because the Open-Meteo model for this afternoon is overcast, not as a clear-day postcard.",
        "alt_text": "AI-generated artistic interpretation of the Jungfrau massif from Harder Kulm above Interlaken under cloud",
        "sky": "Overcast afternoon, gray sky, diffuse light, summits wrapped in cloud but still identifiable, green valley, no fresh snow on the town.",
        "weather_note": "Harder Kulm terrace is about 1322 m. The Open-Meteo cell elevation is about 905 m, so the temperature is the model cell, not a reading on the terrace.",
    },
    {
        "entry_id": "CH-01-004",
        "caption": "Jet d'Eau, Geneva",
        "city": "Geneva",
        "region": "Geneva",
        "folder": "Geneva",
        "lat": 46.2074,
        "lon": 6.1560,
        "viewpoint": "Geneva quay on Lake Geneva, looking toward the offshore Jet d'Eau. Map: https://maps.google.com/?q=46.2074,6.1560 The exact quay stone was not surveyed.",
        "refs": [
            "https://www.geneve.com/en/",
            "https://en.wikipedia.org/wiki/Jet_d%27Eau",
        ],
        "anchors": [
            "One vertical water plume rising from a small structure in the lake, not a multi-jet plaza fountain.",
            "Open lake water between the quay and the jet.",
            "Low far shore; no flower clock and no readable emblem as the subject.",
        ],
        "composition": "Lakefront quay looking toward the single Jet d'Eau plume on Lake Geneva · AI-generated artistic interpretation",
        "description": "A single tall water plume rises from the jet structure offshore in Lake Geneva, seen from the Geneva quay. The lake stretches toward a low far shore under cloud. The jet is the only fountain, and the frame does not include the flower clock or a focal logo. Light is the soft overcast described by the Open-Meteo model for this Geneva afternoon.",
        "alt_text": "AI-generated artistic interpretation of the Jet d'Eau rising from Lake Geneva",
        "sky": "Overcast afternoon, gray sky, soft light, gray-blue lake, no rain, no second fountain.",
    },
    {
        "entry_id": "CH-01-005",
        "caption": "Zytglogge, Bern",
        "city": "Bern",
        "region": "Bern",
        "folder": "Bern",
        "lat": 46.9480,
        "lon": 7.4478,
        "viewpoint": "Kramgasse in Bern’s old town, looking west toward the Zytglogge. Map: https://maps.google.com/?q=46.9480,7.4478 The exact arcade bay was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Zytglogge",
            "https://whc.unesco.org/en/list/267/",
        ],
        "anchors": [
            "Sandstone arcade street of the old town closing on a clock tower.",
            "Zytglogge astronomical clock and pointed tower at the west end of Kramgasse.",
            "No festival banners and no scaffolding added to the UNESCO street.",
        ],
        "composition": "Kramgasse looking west to the Zytglogge clock tower · AI-generated artistic interpretation",
        "description": "The sandstone arcade of Bern’s Kramgasse leads west to the Zytglogge, whose astronomical clock and pointed tower close the street. The old-town roofs stay inside the street canyon. No festival banners or scaffolding are added. The afternoon light is the diffuse overcast given by the Open-Meteo model for Bern.",
        "alt_text": "AI-generated artistic interpretation of the Zytglogge at the end of Kramgasse in Bern",
        "sky": "Overcast afternoon, soft gray light on sandstone, no blue sky, no rain.",
    },
    {
        "entry_id": "CH-01-006",
        "caption": "Limmatquai, Zurich",
        "city": "Zurich",
        "region": "Zurich",
        "folder": "Zurich",
        "lat": 47.3695,
        "lon": 8.5428,
        "viewpoint": "Limmatquai on the right bank of the Limmat, looking along the river with the Grossmünster towers. Map: https://maps.google.com/?q=47.3695,8.5428 The exact quay point was not surveyed.",
        "refs": [
            "https://www.zuerich.com/en/visit/attractions/grossmunster",
            "https://en.wikipedia.org/wiki/Limmatquai",
        ],
        "anchors": [
            "Limmat river with the quay promenade along the right bank.",
            "Grossmünster’s pair of Romanesque towers on the right-bank rise.",
            "Guild-house facades on the water; no commercial logo as the subject.",
        ],
        "composition": "Limmatquai looking along the Limmat toward the Grossmünster twin towers · AI-generated artistic interpretation",
        "description": "The Limmatquai promenade follows the Limmat through Zurich’s old town, with guild-house facades on the water and the Grossmünster’s twin Romanesque towers on the right bank. The river runs through the frame and the quay is free of prominent people. No commercial logo is the subject. Cloud and temperature follow the Open-Meteo model for this Zurich afternoon.",
        "alt_text": "AI-generated artistic interpretation of Limmatquai and the Grossmünster along the Limmat in Zurich",
        "sky": "Overcast afternoon, gray sky, diffuse light, slight breeze on the river, no rain.",
    },
    {
        "entry_id": "CH-01-007",
        "caption": "Staubbach Falls, Lauterbrunnen",
        "city": "Lauterbrunnen",
        "region": "Bern",
        "folder": "Lauterbrunnen",
        "lat": 46.5932,
        "lon": 7.9087,
        "viewpoint": "Lauterbrunnen valley floor looking up at Staubbach Falls on the western cliff. Map: https://maps.google.com/?q=46.5932,7.9087 The exact meadow point was not surveyed.",
        "refs": [
            "https://www.jungfrau.ch/en-gb/",
            "https://en.wikipedia.org/wiki/Staubbach_Falls",
        ],
        "anchors": [
            "Very tall, thin waterfall leaving the lip of a sheer cliff.",
            "Wooden chalets and a church spire at the foot of the wall.",
            "Narrow valley, late-September green meadow, not a wide river cataract.",
        ],
        "composition": "Valley floor looking up at Staubbach Falls above the Lauterbrunnen church · AI-generated artistic interpretation",
        "description": "Staubbach Falls drops as a tall, thin veil from the lip of the western cliff above Lauterbrunnen. Wooden chalets and the church spire sit at the base of the wall, with late-September meadows still green. The fall is the cliff waterfall, not a wide river cataract. The Open-Meteo model for the valley is heavily clouded, and the light is soft.",
        "alt_text": "AI-generated artistic interpretation of Staubbach Falls above Lauterbrunnen",
        "sky": "Heavily overcast afternoon, gray sky, soft light, green valley meadows, no blue sky, no rain curtain beyond the waterfall mist.",
    },
    {
        "entry_id": "CH-01-008",
        "caption": "Gruyères Castle, Gruyères",
        "city": "Gruyères",
        "region": "Fribourg",
        "folder": "Gruyères",
        "lat": 46.5834,
        "lon": 7.0837,
        "viewpoint": "Medieval main street of Gruyères, looking uphill toward the castle. Map: https://maps.google.com/?q=46.5834,7.0837 The exact cobble was not surveyed.",
        "refs": [
            "https://www.chateau-gruyeres.ch/en/",
            "https://en.wikipedia.org/wiki/Gruy%C3%A8res_Castle",
        ],
        "anchors": [
            "Hill town street of medieval houses leading to a castle at the high end.",
            "Castle with round towers and steep roofs above the roofs of the town.",
            "Fribourg pre-Alps behind; no scaffolding on the castle.",
        ],
        "composition": "Medieval street climbing to Gruyères Castle on the hill · AI-generated artistic interpretation",
        "description": "The cobbled main street of Gruyères rises between medieval houses to the castle at the top of the hill, with round towers and steep roofs. The Fribourg pre-Alps sit behind the town. The castle is shown as it stands, without added scaffolding, and the street has no prominent people. Afternoon light is the soft overcast from the Open-Meteo model.",
        "alt_text": "AI-generated artistic interpretation of Gruyères Castle above the medieval street in Gruyères",
        "sky": "Overcast afternoon, gray sky, soft light on stone and plaster, green pre-Alps under cloud.",
    },
    {
        "entry_id": "CH-01-009",
        "caption": "Chillon Castle, Montreux",
        "city": "Montreux",
        "region": "Vaud",
        "folder": "Montreux",
        "lat": 46.4142,
        "lon": 6.9274,
        "viewpoint": "Lake Geneva shore near Montreux, looking toward Chillon Castle on its rock. Map: https://maps.google.com/?q=46.4142,6.9274 The exact shore point was not surveyed.",
        "refs": [
            "https://www.chillon.ch/en/",
            "https://en.wikipedia.org/wiki/Chillon_Castle",
        ],
        "anchors": [
            "Castle on a rock island in Lake Geneva, round and square towers, bridge to the shore.",
            "Water reaching the walls.",
            "Dents du Midi ridge across the lake, softened by cloud.",
        ],
        "composition": "Lake Geneva shore looking toward Chillon Castle and the Dents du Midi · AI-generated artistic interpretation",
        "description": "Chillon Castle stands on its rock in Lake Geneva, a cluster of round and square towers linked to the shore by a bridge. The water reaches the walls, and the Dents du Midi ridge is the mountain backdrop across the lake. The peaks are softened by cloud to match the overcast Open-Meteo model. No boat with a readable name is featured.",
        "alt_text": "AI-generated artistic interpretation of Chillon Castle on Lake Geneva near Montreux",
        "sky": "Overcast afternoon, gray sky, soft light, mountains hazy with cloud, lake gray-blue, no rain.",
    },
    {
        "entry_id": "CH-01-010",
        "caption": "Lake St. Moritz, St. Moritz",
        "city": "St. Moritz",
        "region": "Graubünden",
        "folder": "St. Moritz",
        "lat": 46.4970,
        "lon": 9.8380,
        "viewpoint": "Shore of Lake St. Moritz, looking across the water toward the town and Engadin peaks. Map: https://maps.google.com/?q=46.4970,9.8380 The exact shore point was not surveyed.",
        "refs": [
            "https://www.stmoritz.com/en/",
            "https://en.wikipedia.org/wiki/St._Moritz",
        ],
        "anchors": [
            "Alpine lake in the foreground and the town on the slope.",
            "Engadin peaks behind the town, with residual snow only on higher summits.",
            "Late September: larches mostly green with first gold, town not in winter snow cover.",
        ],
        "composition": "Engadin lakeshore looking across Lake St. Moritz toward the town and peaks · AI-generated artistic interpretation",
        "description": "Lake St. Moritz fills the foreground, with the town climbing the slope and high Engadin peaks behind it. Late September here is early autumn: larches are still mostly green with only the first gold, and the town is not under winter snow. Residual snow is limited to the higher summits. The Open-Meteo model for this high cell is fully overcast.",
        "alt_text": "AI-generated artistic interpretation of Lake St. Moritz and the Engadin town under cloud",
        "sky": "Fully overcast afternoon at altitude, gray sky, no blue, town and lake free of winter snow, only high summits holding residual snow, larches just starting to turn.",
    },
    {
        "entry_id": "CH-01-011",
        "caption": "Appenzell, Appenzell",
        "city": "Appenzell",
        "region": "Appenzell Innerrhoden",
        "folder": "Appenzell",
        "lat": 47.3314,
        "lon": 9.4096,
        "viewpoint": "Appenzell village center, looking across painted wooden houses toward the Alpstein. Map: https://maps.google.com/?q=47.3314,9.4096 The exact square point was not surveyed.",
        "refs": [
            "https://www.appenzell.ch/en/",
            "https://en.wikipedia.org/wiki/Appenzell_(village)",
        ],
        "anchors": [
            "Painted wooden gables and a village church, not a generic chalet row.",
            "Limestone ridges of the Alpstein behind the roofs.",
            "Public square without prominent people.",
        ],
        "composition": "Village center with painted wooden houses and the Alpstein behind · AI-generated artistic interpretation",
        "description": "Appenzell’s village center shows painted wooden gables and the church, with the limestone ridges of the Alpstein rising behind the roofs. The street is a public square, empty of prominent people. Houses keep traditional painted fronts rather than a generic chalet row. The Open-Meteo model is overcast and breezy for this afternoon.",
        "alt_text": "AI-generated artistic interpretation of Appenzell village with painted houses and the Alpstein",
        "sky": "Overcast and breezy afternoon, gray sky, soft light, green pastures, Alpstein limestone partly in cloud.",
    },
    {
        "entry_id": "CH-01-012",
        "caption": "Lugano lakefront, Lugano",
        "city": "Lugano",
        "region": "Ticino",
        "folder": "Lugano",
        "lat": 46.0037,
        "lon": 8.9511,
        "viewpoint": "Lugano lakefront promenade, looking across the lake toward Monte Brè and Monte San Salvatore. Map: https://maps.google.com/?q=46.0037,8.9511 The exact promenade point was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Lugano",
            "https://en.wikipedia.org/wiki/Monte_Br%C3%A8",
        ],
        "anchors": [
            "Lake Lugano with a palm-lined promenade in the foreground.",
            "Monte Brè and Monte San Salvatore framing the water.",
            "Subtropical lakeside vegetation still green in late September; mountains softened by cloud.",
        ],
        "composition": "Lugano lakefront promenade toward the lake, Monte Brè, and Monte San Salvatore · AI-generated artistic interpretation",
        "description": "The Lugano lakefront promenade faces Lake Lugano, with palms and waterfront buildings in front of Monte Brè and Monte San Salvatore. Ticino vegetation is still green in late September. The mountains are close and partly softened by cloud. The Open-Meteo model for this afternoon is overcast, with little wind and no rain.",
        "alt_text": "AI-generated artistic interpretation of the Lugano lakefront with Monte Brè under cloud",
        "sky": "Overcast afternoon, gray sky, soft light, green palms, lake gray-blue, mountains close and cloud-softened, no rain.",
    },
    {
        "entry_id": "CH-01-013",
        "caption": "Mittlere Brücke, Basel",
        "city": "Basel",
        "region": "Basel-Stadt",
        "folder": "Basel",
        "lat": 47.5596,
        "lon": 7.5903,
        "viewpoint": "Rhine bank in Basel looking along Mittlere Brücke toward the chapel on the bridge and the Münster. Map: https://maps.google.com/?q=47.5596,7.5903 The exact quay point was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Mittlere_Br%C3%BCcke",
            "https://en.wikipedia.org/wiki/Basel_Minster",
        ],
        "anchors": [
            "Stone bridge across the Rhine with a small chapel on the bridge.",
            "Red-sandstone Basel Münster on the rise above the south bank.",
            "No commercial banners added to the bridge.",
        ],
        "composition": "Rhine and Mittlere Brücke with the bridge chapel and Basel Münster · AI-generated artistic interpretation",
        "description": "The Mittlere Brücke crosses the Rhine in Basel, with the small chapel on the bridge and the red-sandstone Basel Münster on the rise above the south bank. The quays are quiet and no commercial banners are added to the bridge. The Open-Meteo model for this afternoon is overcast and windy, with no rain.",
        "alt_text": "AI-generated artistic interpretation of Mittlere Brücke and Basel Münster on the Rhine",
        "sky": "Overcast windy afternoon, gray sky, soft light, gray-green Rhine, no rain.",
    },
    {
        "entry_id": "CH-01-014",
        "caption": "Thun Castle, Thun",
        "city": "Thun",
        "region": "Bern",
        "folder": "Thun",
        "lat": 46.7584,
        "lon": 7.6298,
        "viewpoint": "Thun old town toward the castle keep, with the Aare and a glimpse of the lake. Map: https://maps.google.com/?q=46.7584,7.6298 The exact street point was not surveyed.",
        "refs": [
            "https://schlossthun.ch/",
            "https://en.wikipedia.org/wiki/Thun_Castle",
        ],
        "anchors": [
            "Massive square keep with four corner towers and steep roofs above the roofs.",
            "Aare river through the town toward Lake Thun.",
            "Alps only faint under cloud; no construction cranes on the castle.",
        ],
        "composition": "Old town and Aare toward Thun Castle, with Lake Thun beyond · AI-generated artistic interpretation",
        "description": "Thun Castle’s great square keep and four corner towers rise above the old-town roofs. The Aare runs through the town toward Lake Thun, with the Alps faint under cloud. The castle is the historic keep, without construction cranes. The Open-Meteo model for this afternoon is overcast.",
        "alt_text": "AI-generated artistic interpretation of Thun Castle above the old town and the Aare",
        "sky": "Overcast afternoon, gray sky, soft light, lake and river visible, Alps only a faint shape in cloud.",
    },
    {
        "entry_id": "CH-01-015",
        "caption": "Eiger, Grindelwald",
        "city": "Grindelwald",
        "region": "Bern",
        "folder": "Grindelwald",
        "lat": 46.6242,
        "lon": 8.0414,
        "viewpoint": "Grindelwald valley meadows, looking south at the Eiger north face. Map: https://maps.google.com/?q=46.6242,8.0414 The exact meadow point was not surveyed. Weather cell is the valley, not the summit.",
        "refs": [
            "https://grindelwald.swiss/en/",
            "https://en.wikipedia.org/wiki/Eiger",
        ],
        "anchors": [
            "Eiger north face as a dark near-vertical wall, not a generic snow pyramid.",
            "Mönch and Jungfrau further west (right when looking south); Wetterhorn to the east (left).",
            "Valley meadows and chalets in late-September green; no invented climbing infrastructure on the wall.",
        ],
        "composition": "Grindelwald meadows looking south at the Eiger north face · AI-generated artistic interpretation",
        "description": "From the Grindelwald valley, the Eiger’s north face is a dark, near-vertical wall, with the Mönch and Jungfrau further west and the Wetterhorn to the east. Meadows and wooden chalets sit in the foreground under late-September green. The Open-Meteo valley model is overcast with partial cloud cover, so the upper wall carries cloud while the face stays identifiable. No climbing infrastructure is invented on the wall.",
        "alt_text": "AI-generated artistic interpretation of the Eiger north face from Grindelwald",
        "sky": "Valley overcast with breaks, gray sky, upper north face wearing cloud, lower rock wall visible, green meadows, no midwinter snow in the village.",
    },
    {
        "entry_id": "CH-01-016",
        "caption": "Rhine Falls, Schaffhausen",
        "city": "Schaffhausen",
        "region": "Schaffhausen",
        "folder": "Schaffhausen",
        "lat": 47.6779,
        "lon": 8.6155,
        "viewpoint": "North-bank viewpoint at the Rhine Falls, looking across the falls toward Schloss Laufen. Map: https://maps.google.com/?q=47.6779,8.6155 The exact platform was not surveyed.",
        "refs": [
            "https://www.rheinfall.ch/en/",
            "https://en.wikipedia.org/wiki/Rhine_Falls",
        ],
        "anchors": [
            "Wide falls breaking around a central rock in the Rhine.",
            "Schloss Laufen on the south cliff and Schloss Wörth on the near bank.",
            "Only the real visitor railings at the viewpoint; no extra invented scaffolding.",
        ],
        "composition": "Rhine Falls from the north bank, with the mid-river rock and Schloss Laufen · AI-generated artistic interpretation",
        "description": "The Rhine Falls spreads wide across the river, breaking around the central rock, with Schloss Laufen on the south cliff and Schloss Wörth on the near side. Existing visitor railings belong to the real viewpoint and are not expanded into new scaffolding. Spray and gray water match a cloudy afternoon. The Open-Meteo model is overcast and windy, with no rain.",
        "alt_text": "AI-generated artistic interpretation of the Rhine Falls near Schaffhausen",
        "sky": "Overcast windy afternoon, gray sky, soft light, gray water and spray, no blue sky, no rain shafts.",
    },
    {
        "entry_id": "CH-01-017",
        "caption": "Allalinhorn, Saas-Fee",
        "city": "Saas-Fee",
        "region": "Valais",
        "folder": "Saas-Fee",
        "lat": 46.078,
        "lon": 7.898,
        "viewpoint": "Längfluh balcony above Saas-Fee, looking south toward the Allalinhorn and the Fee Glacier. Map: https://maps.google.com/?q=46.078,7.898 The exact rock was not surveyed.",
        "refs": [
            "https://www.saas-fee.ch/en",
            "https://en.wikipedia.org/wiki/Allalinhorn",
        ],
        "anchors": [
            "Allalinhorn as a snow-and-ice summit on a high ridge, not a lone Matterhorn-style pyramid.",
            "Fee Glacier in the middle ground, crevassed, flowing from the peak toward the viewpoint.",
            "Rocky Längfluh foreground; no new cableway or construction crane.",
        ],
        "composition": "Längfluh balcony looking south to the Allalinhorn and the Fee Glacier · AI-generated artistic interpretation",
        "description": "From the Längfluh balcony above Saas-Fee, the Allalinhorn rises as a snow-and-ice summit on the high ridge, with the Fee Glacier crevassed in the middle ground. Dark rock ribs frame the ice, and the near slope is late-September rock and tawny alpine turf. The Open-Meteo cell for this balcony is mainly clear, so the peak stays readable under only a few fair-weather clouds. No new lift or crane is added.",
        "alt_text": "AI-generated artistic interpretation of the Allalinhorn and Fee Glacier from Längfluh above Saas-Fee",
        "sky": "Mainly clear high-alpine afternoon, sun visible from the south-southwest, low cloud cover, a few small fair-weather clouds, blue sky, no precipitation, permanent snow and ice only on the peak and glacier.",
        "weather_note": "The Längfluh viewpoint is about 2870 m. The temperature is the Open-Meteo model cell, not a thermometer on the balcony.",
    },
    {
        "entry_id": "CH-01-018",
        "caption": "Aletsch Glacier, Bettmeralp",
        "city": "Bettmeralp",
        "region": "Valais",
        "folder": "Bettmeralp",
        "lat": 46.3909,
        "lon": 8.0758,
        "viewpoint": "Bettmerhorn viewpoint above Bettmeralp, looking along the Great Aletsch Glacier. Map: https://maps.google.com/?q=46.3909,8.0758 The exact platform was not surveyed.",
        "refs": [
            "https://www.aletscharena.ch/en",
            "https://en.wikipedia.org/wiki/Aletsch_Glacier",
        ],
        "anchors": [
            "Great Aletsch Glacier as a long ice stream seen from above, with dark medial moraines and a broad curve.",
            "High peaks closing the head of the glacier, softened by cloud.",
            "Rocky ridge foreground at the Bettmerhorn viewpoint; no invented construction.",
        ],
        "composition": "Bettmerhorn viewpoint above Bettmeralp looking along the Great Aletsch Glacier · AI-generated artistic interpretation",
        "description": "From the Bettmerhorn viewpoint above Bettmeralp, the Great Aletsch Glacier runs as a long, crevassed ice stream marked by dark medial moraines and a wide curve. High peaks close the head of the ice and sit in cloud. The near ground is rock and low late-September alpine vegetation. The Open-Meteo model for this cell is overcast, so the light on the ice is flat and gray. No construction is added.",
        "alt_text": "AI-generated artistic interpretation of the Great Aletsch Glacier from Bettmerhorn above Bettmeralp",
        "sky": "Fully overcast afternoon, gray sky, diffuse light, no blue patches, no rain, glacier under flat light.",
        "weather_note": "The Bettmerhorn viewpoint is about 2647 m. The Open-Meteo cell is lower, so the temperature is the model cell, not a thermometer on the platform.",
    },
    {
        "entry_id": "CH-01-019",
        "caption": "Valère Basilica, Sion",
        "city": "Sion",
        "region": "Valais",
        "folder": "Sion",
        "lat": 46.2339,
        "lon": 7.3644,
        "viewpoint": "Sion, looking up at the fortified Valère Basilica on its hill, with the Tourbillon ruin on the opposite hill. Map: https://maps.google.com/?q=46.2339,7.3644 The exact street point was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Val%C3%A8re_Basilica",
            "https://siontourisme.ch/en/valere",
        ],
        "anchors": [
            "Fortified Romanesque-Gothic basilica and walled hilltop borough, with a square belfry.",
            "Ruined Tourbillon castle on the facing hill.",
            "Dry late-September slopes and the Rhône valley below; no scaffolding.",
        ],
        "composition": "Sion looking up to the fortified Valère Basilica, with Tourbillon on the opposite hill · AI-generated artistic interpretation",
        "description": "The fortified Valère Basilica crowns its hill above Sion, a Romanesque and Gothic church inside a walled hilltop borough, with a square belfry and the old canon houses. The ruined Tourbillon castle occupies the opposite hill. Dry late-September grass and the valley town sit below. The Open-Meteo model is partly cloudy and warm, and no scaffolding is added.",
        "alt_text": "AI-generated artistic interpretation of the fortified Valère Basilica above Sion",
        "sky": "Partly cloudy warm afternoon, sun and broken cumulus, dry golden slopes, no rain.",
    },
    {
        "entry_id": "CH-01-020",
        "caption": "Mount Pilatus, Lucerne",
        "city": "Lucerne",
        "region": "Lucerne",
        "folder": "Lucerne",
        "lat": 47.0532,
        "lon": 8.3125,
        "viewpoint": "Lucerne lakeshore, looking southwest toward the Pilatus massif. Map: https://maps.google.com/?q=47.0532,8.3125 The exact quay point was not surveyed.",
        "refs": [
            "https://www.pilatus.ch/en/",
            "https://en.wikipedia.org/wiki/Pilatus_(mountain)",
        ],
        "anchors": [
            "Jagged limestone massif with several rocky summits, not a single snow pyramid.",
            "Lake Lucerne in the foreground and the city shore.",
            "No covered wooden bridge and no water tower; those belong to the Chapel Bridge scene.",
        ],
        "composition": "Lucerne lakeshore looking southwest to the Pilatus massif · AI-generated artistic interpretation",
        "description": "From the Lucerne lakeshore, Mount Pilatus rises as a steep, jagged limestone massif southwest of the city, with several rocky summits rather than one snow pyramid. The lake fills the foreground under gray light. This frame keeps to the open shore and does not use the Chapel Bridge or the Water Tower. The Open-Meteo model is overcast, with no rain.",
        "alt_text": "AI-generated artistic interpretation of Mount Pilatus from the Lucerne lakeshore",
        "sky": "Fully overcast afternoon, gray sky, soft diffuse light, gray-blue lake, no rain, no hard shadows.",
    },
    {
        "entry_id": "CH-01-021",
        "caption": "Mount Rigi, Vitznau",
        "city": "Vitznau",
        "region": "Lucerne",
        "folder": "Vitznau",
        "lat": 47.01,
        "lon": 8.483,
        "viewpoint": "Vitznau shore of Lake Lucerne, looking north at Mount Rigi. Map: https://maps.google.com/?q=47.010,8.483 The exact quay point was not surveyed.",
        "refs": [
            "https://www.rigi.ch/en",
            "https://en.wikipedia.org/wiki/Rigi",
        ],
        "anchors": [
            "Broad forested Rigi ridge rising directly behind Vitznau.",
            "Lake Lucerne in the foreground and the lakeside village at the foot of the slope.",
            "The cog railway is only a thin line on the mountain. No readable boat name.",
        ],
        "composition": "Vitznau shore looking north at the forested ridge of Mount Rigi · AI-generated artistic interpretation",
        "description": "From the Vitznau shore, Mount Rigi rises directly behind the village as a broad, forested ridge. Lake Lucerne is the foreground, and the cog-railway line is only a thin trace on the slope. No boat with a readable name is featured. Pastures are still green in late September. The Open-Meteo model is overcast, with soft light and no rain.",
        "alt_text": "AI-generated artistic interpretation of Mount Rigi from the Vitznau shore of Lake Lucerne",
        "sky": "Fully overcast afternoon, gray sky, soft light, gray-blue lake, green forested ridge, no rain.",
    },
    {
        "entry_id": "CH-01-022",
        "caption": "Bundeshaus, Bern",
        "city": "Bern",
        "region": "Bern",
        "folder": "Bern",
        "lat": 46.9465,
        "lon": 7.4443,
        "viewpoint": "Bundesplatz in Bern, looking north at the Bundeshaus facade. Map: https://maps.google.com/?q=46.9465,7.4443 The exact paving point was not surveyed.",
        "refs": [
            "https://www.parlament.ch/en",
            "https://en.wikipedia.org/wiki/Federal_Palace_of_Switzerland",
        ],
        "anchors": [
            "Symmetrical sandstone palace with a central dome and two long wings.",
            "Open square in front, with a low fountain and no crowd.",
            "No banners, scaffolding, or readable inscription as the subject.",
        ],
        "composition": "Bundesplatz looking north at the Bundeshaus facade · AI-generated artistic interpretation",
        "description": "The Bundeshaus closes the north side of Bundesplatz, a symmetrical sandstone palace with a central dome and two long wings. The open square and a low fountain lead to the facade. No banners, scaffolding, or readable inscription are added, and the square is free of prominent people. Afternoon light is the soft overcast given by the Open-Meteo model for Bern.",
        "alt_text": "AI-generated artistic interpretation of the Bundeshaus from Bundesplatz in Bern",
        "sky": "Fully overcast afternoon, soft gray light on sandstone, no blue sky, no rain, empty square.",
    },
    {
        "entry_id": "CH-01-023",
        "caption": "Wengen, Wengen",
        "city": "Wengen",
        "region": "Bern",
        "folder": "Wengen",
        "lat": 46.6054,
        "lon": 7.921,
        "viewpoint": "Wengen village terrace, looking south toward the Jungfrau wall behind the roofs. Map: https://maps.google.com/?q=46.6054,7.921 The exact lane point was not surveyed.",
        "refs": [
            "https://www.wengen.swiss/en/",
            "https://en.wikipedia.org/wiki/Wengen",
        ],
        "anchors": [
            "Car-free wooden chalet village and a church on a terrace.",
            "Jungfrau snow wall close behind the roofs, with cloud on the high face.",
            "No cars. Late-September green meadows, and the village is not under winter snow.",
        ],
        "composition": "Wengen terrace of wooden chalets with the Jungfrau wall behind the roofs · AI-generated artistic interpretation",
        "description": "Wengen’s car-free terrace of wooden chalets and the village church sits above the valley, with the Jungfrau wall close behind the roofs. Meadows are still green in late September, and snow and ice stay on the high face. The upper mountain carries cloud because the Open-Meteo model is heavily overcast. No road traffic is shown.",
        "alt_text": "AI-generated artistic interpretation of Wengen with the Jungfrau wall behind the village",
        "sky": "Heavily overcast afternoon, gray sky, soft light, high faces in cloud, green meadows, no snow in the village, no rain.",
    },
    {
        "entry_id": "CH-01-024",
        "caption": "Mürren, Mürren",
        "city": "Mürren",
        "region": "Bern",
        "folder": "Mürren",
        "lat": 46.5594,
        "lon": 7.8923,
        "viewpoint": "Mürren cliff shelf, looking across the valley to the Eiger north face. Map: https://maps.google.com/?q=46.5594,7.8923 The exact path point was not surveyed.",
        "refs": [
            "https://www.muerren.swiss/en/",
            "https://en.wikipedia.org/wiki/M%C3%BCrren",
        ],
        "anchors": [
            "Cliff-edge car-free village, with the ground falling away.",
            "Eiger north face across the valley, dark rock, cloud on the upper wall.",
            "The mountain is across the trench, not rising immediately behind the roofs as at Wengen.",
        ],
        "composition": "Mürren cliff shelf looking across the valley to the Eiger north face · AI-generated artistic interpretation",
        "description": "Mürren stands on a narrow cliff shelf, wooden chalets and a church looking across the deep valley to the Eiger’s dark north face. The village is car-free, and the path along the edge is empty of prominent people. Late-September grass is green to tawny, and the village is not under winter snow. The Open-Meteo model is overcast, so cloud sits on the upper wall while the face stays identifiable.",
        "alt_text": "AI-generated artistic interpretation of Mürren on its cliff with the Eiger north face across the valley",
        "sky": "Overcast afternoon with heavy cloud, gray sky, upper north face in cloud, lower rock wall visible, green shelf, no rain, no village snow.",
    },
    {
        "entry_id": "CH-01-025",
        "caption": "Brienz, Brienz",
        "city": "Brienz",
        "region": "Bern",
        "folder": "Brienz",
        "lat": 46.754,
        "lon": 8.0315,
        "viewpoint": "Brienz lakeshore, looking along Lake Brienz past the wooden village. Map: https://maps.google.com/?q=46.754,8.0315 The exact quay point was not surveyed.",
        "refs": [
            "https://www.brienz.ch/",
            "https://en.wikipedia.org/wiki/Brienz",
        ],
        "anchors": [
            "Lakeside wooden village and church on Lake Brienz.",
            "Long lake and steep wooded slopes, with the Brienzer Rothorn ridge in cloud.",
            "The village on one lake, not the Interlaken two-lake panorama.",
        ],
        "composition": "Brienz wooden village along the shore of Lake Brienz · AI-generated artistic interpretation",
        "description": "Brienz lines the shore of Lake Brienz with wooden houses and a church, and the water stretches toward steep wooded slopes. The Brienzer Rothorn ridge is softened by cloud. The lake is gray-green under the overcast model, and the village is the subject rather than the Interlaken panorama. The Open-Meteo model shows no rain.",
        "alt_text": "AI-generated artistic interpretation of Brienz along the shore of Lake Brienz",
        "sky": "Fully overcast afternoon, gray sky, soft light, gray-green lake, wooded slopes in cloud, no rain.",
    },
    {
        "entry_id": "CH-01-026",
        "caption": "Grossmünster, Zurich",
        "city": "Zurich",
        "region": "Zurich",
        "folder": "Zurich",
        "lat": 47.3702,
        "lon": 8.5443,
        "viewpoint": "Church square at the west front of the Grossmünster. Map: https://maps.google.com/?q=47.3702,8.5443 The exact paving point was not surveyed.",
        "refs": [
            "https://www.zuerich.com/en/visit/attractions/grossmunster",
            "https://en.wikipedia.org/wiki/Grossm%C3%BCnster",
        ],
        "anchors": [
            "Twin Romanesque towers with later pointed caps, seen from the west front.",
            "Paved church square in front, with no river and no quay.",
            "Interior windows and portal doors are not the subject.",
        ],
        "composition": "West front of the Grossmünster from the church square · AI-generated artistic interpretation",
        "description": "The Grossmünster’s twin Romanesque towers and west facade fill the frame from the paved square in front of the church. The towers carry their later pointed caps and stand close together above the portal. This view is the church front, not the Limmatquai river promenade, and the interior windows are not shown. Cloud and light follow the overcast Open-Meteo model for Zurich.",
        "alt_text": "AI-generated artistic interpretation of the Grossmünster west front in Zurich",
        "sky": "Fully overcast afternoon, gray sky, soft light on stone, no river in frame, no rain.",
    },
    {
        "entry_id": "CH-01-027",
        "caption": "Uetliberg, Zurich",
        "city": "Zurich",
        "region": "Zurich",
        "folder": "Zurich",
        "lat": 47.3494,
        "lon": 8.4913,
        "viewpoint": "Uetliberg summit terrace, looking over Zurich and Lake Zurich. Map: https://maps.google.com/?q=47.3494,8.4913 The exact terrace point was not surveyed.",
        "refs": [
            "https://www.zuerich.com/en",
            "https://en.wikipedia.org/wiki/Uetliberg",
        ],
        "anchors": [
            "Summit terrace and slim lookout above beech woods.",
            "Zurich and the long sheet of Lake Zurich in the middle distance.",
            "Alps only faint or hidden under the overcast model.",
        ],
        "composition": "Uetliberg summit terrace over Zurich and Lake Zurich · AI-generated artistic interpretation",
        "description": "From the Uetliberg summit terrace, Zurich spreads between wooded hills and Lake Zurich runs south. Beech woods at the summit are still mostly green, with only the first late-September turn. Under the fully overcast Open-Meteo model the distant Alps stay faint or hidden, and the city and lake remain the readable view. No readable billboard is featured.",
        "alt_text": "AI-generated artistic interpretation of Zurich and Lake Zurich from the Uetliberg summit",
        "sky": "Fully overcast afternoon, gray sky, soft light, city and lake visible, Alps faint or hidden, beech woods mostly green, no rain.",
        "weather_note": "The Uetliberg summit is about 870 m. The temperature is the Open-Meteo model cell, not a thermometer on the terrace.",
    },
    {
        "entry_id": "CH-01-028",
        "caption": "Rapperswil Castle, Rapperswil",
        "city": "Rapperswil",
        "region": "St. Gallen",
        "folder": "Rapperswil",
        "lat": 47.2269,
        "lon": 8.8157,
        "viewpoint": "Lake side of the Rapperswil peninsula, looking toward the castle and the parish church on the knoll. Map: https://maps.google.com/?q=47.2269,8.8157 The exact shore point was not surveyed.",
        "refs": [
            "https://schlossrapperswil.ch/",
            "https://en.wikipedia.org/wiki/Rapperswil_Castle",
        ],
        "anchors": [
            "Three-towered castle and palas on the rocky end of the peninsula, with the parish church beside it.",
            "Lake Zurich on both sides of the old town.",
            "The long wooden bridge may appear to one side as the existing lake crossing. No scaffolding.",
        ],
        "composition": "Rapperswil peninsula with the castle and parish church above the old town · AI-generated artistic interpretation",
        "description": "Rapperswil Castle stands on the rocky end of the peninsula, a three-towered Schloss and palas above the old-town roofs, with the parish church beside it and Lake Zurich on both sides. The long wooden bridge can cross the water to one side, as the existing lake crossing. Rapperswil is the locality in the municipality of Rapperswil-Jona, canton of St. Gallen, on the upper lake opposite the Zurich shore. The Open-Meteo model is overcast and breezy, and no scaffolding is added.",
        "alt_text": "AI-generated artistic interpretation of Rapperswil Castle on its peninsula in Lake Zurich",
        "sky": "Fully overcast breezy afternoon, gray sky, soft light, small ripples on the lake, no rain.",
    },
    {
        "entry_id": "CH-01-029",
        "caption": "St. Pierre Cathedral, Geneva",
        "city": "Geneva",
        "region": "Geneva",
        "folder": "Geneva",
        "lat": 46.2012,
        "lon": 6.1483,
        "viewpoint": "Old-town square at the west front of St. Pierre Cathedral. Map: https://maps.google.com/?q=46.2012,6.1483 The exact paving point was not surveyed.",
        "refs": [
            "https://www.geneve.com/en/",
            "https://en.wikipedia.org/wiki/St._Pierre_Cathedral",
        ],
        "anchors": [
            "Gothic cathedral with a neoclassical columned portico and triangular pediment.",
            "North tower and spire above the old-town square.",
            "No Jet d'Eau and no lake fountain; the old town is the setting.",
        ],
        "composition": "Old-town square at the neoclassical west front of St. Pierre Cathedral · AI-generated artistic interpretation",
        "description": "St. Pierre Cathedral rises in Geneva’s old town, its neoclassical portico and Gothic body topped by the north tower. The paved square is quiet, and the surrounding roofs stay inside the old town. The Jet d'Eau is not in this frame. Light is the soft overcast described by the Open-Meteo model for Geneva, and no focal emblem is added.",
        "alt_text": "AI-generated artistic interpretation of St. Pierre Cathedral in Geneva’s old town",
        "sky": "Fully overcast afternoon, warm gray light on stone, no blue sky, no rain, no water jet.",
    },
    {
        "entry_id": "CH-01-030",
        "caption": "Fribourg Cathedral, Fribourg",
        "city": "Fribourg",
        "region": "Fribourg",
        "folder": "Fribourg",
        "lat": 46.8063,
        "lon": 7.1631,
        "viewpoint": "Lower old town of Fribourg, looking up to St. Nicholas Cathedral above the Sarine. Map: https://maps.google.com/?q=46.8063,7.1631 The exact street point was not surveyed.",
        "refs": [
            "https://www.fribourgtourisme.ch/en/",
            "https://en.wikipedia.org/wiki/Fribourg_Cathedral",
        ],
        "anchors": [
            "Gothic cathedral with one very tall slender tower and spire.",
            "Old-town houses stepping down a rocky hill above the Sarine gorge.",
            "A bridge in the gorge below; no scaffolding on the cathedral.",
        ],
        "composition": "Fribourg old town looking up to St. Nicholas Cathedral above the Sarine · AI-generated artistic interpretation",
        "description": "St. Nicholas Cathedral, the Fribourg Cathedral, stands on the rocky hill above the Sarine, a Gothic church with one tall tower over the old-town roofs. Houses step down the slope toward the gorge, where a bridge crosses the river. The cathedral is shown as it stands, without scaffolding. The Open-Meteo model is heavily clouded, with soft afternoon light and no rain.",
        "alt_text": "AI-generated artistic interpretation of Fribourg Cathedral above the Sarine gorge",
        "sky": "Mostly overcast afternoon, gray sky with only slight lighter breaks, soft light, no rain.",
    },
    {
        "entry_id": "CH-01-031",
        "caption": "Lavaux vineyards, Rivaz",
        "city": "Rivaz",
        "region": "Vaud",
        "folder": "Rivaz",
        "lat": 46.4755,
        "lon": 6.7868,
        "viewpoint": "Vineyard terraces above Rivaz, looking south over Lake Geneva. Map: https://maps.google.com/?q=46.4755,6.7868 The exact terrace was not surveyed.",
        "refs": [
            "https://en.wikipedia.org/wiki/Lavaux",
            "https://whc.unesco.org/en/list/1243/",
        ],
        "anchors": [
            "Stone-walled vineyard terraces stepping down to the lake.",
            "Rivaz and the shore below, with the Alps across the water softened by cloud.",
            "Late-September vines turning yellow and gold. No castle as the subject.",
        ],
        "composition": "Lavaux stone terraces above Rivaz looking over Lake Geneva · AI-generated artistic interpretation",
        "description": "Stone-walled vineyard terraces step down from the slope above Rivaz to Lake Geneva, with the village and the shore below. In late September the vines are turning yellow and gold at harvest, not full summer green. The Alps across the lake are only a faint shape under the overcast Open-Meteo model. The terraces are the subject, and Chillon Castle is not in the frame.",
        "alt_text": "AI-generated artistic interpretation of the Lavaux vineyard terraces above Rivaz",
        "sky": "Fully overcast afternoon, gray sky, soft light, vines yellow and gold with some green, gray-blue lake, Alps faint, no rain.",
    },
    {
        "entry_id": "CH-01-032",
        "caption": "Piazza Grande, Locarno",
        "city": "Locarno",
        "region": "Ticino",
        "folder": "Locarno",
        "lat": 46.1703,
        "lon": 8.7995,
        "viewpoint": "Piazza Grande, looking along the arcaded square toward the lake end. Map: https://maps.google.com/?q=46.1703,8.7995 The exact paving point was not surveyed.",
        "refs": [
            "https://www.ascona-locarno.com/en/",
            "https://en.wikipedia.org/wiki/Locarno",
        ],
        "anchors": [
            "Long rectangular square with continuous arcades on both long sides.",
            "Shuttered facades, stone pavement, and a few palms, opening toward the lake.",
            "No film-festival branding, screen, or red carpet.",
        ],
        "composition": "Piazza Grande in Locarno, arcades along the square toward the lake · AI-generated artistic interpretation",
        "description": "Piazza Grande is a long open rectangle in Locarno, lined with continuous stone arcades and shuttered facades and opening toward the lake light at one end. Palms edge the square in the warm Ticino afternoon. No festival branding or readable logo is the subject, and the square is free of prominent people. The Open-Meteo model is overcast, with soft light and no rain.",
        "alt_text": "AI-generated artistic interpretation of Piazza Grande in Locarno",
        "sky": "Overcast warm afternoon, high cloud cover, soft light, stone square and palms, no rain, no festival staging.",
    },
]
